### ISSUE TITLE
Unnecessary code?

### ISSUE THREAD

**Issue by 42B** [datasets/natural-gas#4]
https://github.com/datasets/natural-gas-prices/blob/ad98a8b2473dcca71bcb6b54d26aba921f4f118a/scripts/process.py#L43-L44

I'm curious what the second line is supposed to be doing? `formated_date` parses `pre_date` and then formats it back exactly the same as it was before.

### Example
```python
>>> pre_date = '2018-01-15'
>>> from datetime import datetime
>>> d = datetime.strptime((str(pre_date)), "%Y-%m-%d").strftime('%Y-%m-%d')
>>> pre_date == d
True
```

It seems like this, `formatted_date = str(pre_date)`, would do the same thing?

**Comment by rufuspollock** [comment]
@42B thanks for the suggestion. @zelima can you check this and correct if appropriate.

**Comment by zelima** [comment]
FIXED
